### ISSUE TITLE
Cookie Banner does not display

### ISSUE THREAD

**Issue by chris7of9** [Godsont/Cookie-Consent-Banner#1]
Checked, double and triple checked my code to your, imported your code in case I was simply missing a basic error, but still - Cookie banner does not display.
 .cookie-container {
  position: fixed;
  bottom: -100%;

Clearly this moves it out of view, but if 
bottom: 0;
Then, yes. Button displayed but when clicked does not disappear -

any suggestions as to what error is, would be much appreciated. - Its actually the only thing stopping the website going live!

https://github.com/Godsont/Cookie-Consent-Banner/blob/master/index.html
https://github.com/Godsont/Cookie-Consent-Banner/blob/master/main.js
https://github.com/Godsont/Cookie-Consent-Banner/blob/master/style.css

**Comment by RicardoSo** [comment]
Hi Cris,

I had the same problem. Finally it is working now, after I made two steps. The first step: In my case the js file was not properly include in my building process.
The second step: I replace part of the strategy to display/hide the cookie consent bar. The original code used the bottom property in CSS (-100 to hide, 0 to display), I only used the display property (display: none to hide).

Hope you find a simple way to solve your case.

**Comment by chris7of9** [comment]
Appreciate the reply Richardo, but I think the issue is the button never becomes active - so this does not owrk
cookieButton.addEventListener("click", () => {
  cookieContainer.classList.remove("active");
  localStorage.setItem("cookieBannerDisplayed", "true");
});

I know the js file is correctly called as I tested it with another  button script which works perfectly;-
const element = document.getElementById("myBtn");
element.addEventListener("mouseover", myFunction);
element.addEventListener("click", mySecondFunction);
element.addEventListener("mouseout", myThirdFunction);

function myFunction() {
  document.getElementById("demo").innerHTML += "Moused over!<br>"
}

function mySecondFunction() {
  document.getElementById("demo").innerHTML += "Clicked!<br>"
}

function myThirdFunction() {
  document.getElementById("demo").innerHTML += "Moused out!<br>"
}


Also I tested by changing the original code to also change the colours, but that doesnt happen - so cant figure why its not active once clicked.
.cookie-container.active {

  bottom: 0;
  background: blue;
  color: white;
}

**Comment by Godsont** [comment]
Hi, the code is set to display the cookie just once on a browser (unless the visitor decides not to click on the Okay button). Once the 'Okay' button is clicked, a localstorage value is created in the browser called 'cookieBannerDisplayed'. Once you have that value, the cookie is no longer displayed. If you want to test it again, you can open the design in an Incognito window. Or just delete the localstorage value from the browser. For Chrome, you can right-click, go to Inspect, click on Application -> Storage -> Local Storage -> Select the website and simply delete the key called 'cookieBannerDisplayed'. Now, you can view the cookie banner once again. 
I just downloaded the code and everything seems to be working alright.
Please let me know if you have any more issues.

**Comment by RicardoSo** [comment]
Hi @chris7of9 , I saw you tested the JS script is properly used with other events. Sorry I don't have any other ideas.

Hi @Godsont ,  thanks a lot for your original solution, very simple and clean!

**Comment by chris7of9** [comment]
Thanks Godsont - your comment prompted me to change the localstorage to session and then I could see all was indeed working.

Next Question would be - what, legally, should one do if client REJECTs cookie storage?
